#!/bin/sh
expect() {
  _n="$1"
  if test -f "$i.exp.$_n"
  then
    while read expect
    do
      echo "    Expecting '$expect' in $i.run.$_n"
      if ! fgrep -F -e "$expect" "$i.run.$_n" >/dev/null
      then
        echo "    FAIL: Expected '$expect' in $i.run.$_n" 1>&2
        fail=`expr $fail + 1`
      fi
    done < "$i.exp.$_n"
  fi
}

pass=0; fail=0
base_cmd="$1"; shift
for i in "$@"
do
   [ "$i" = "t/test-func.in" ] && continue
   cmd="$base_cmd $i > $i.run.out 2> $i.run.err"
   echo "  Test: $i"
   echo "  Run: $cmd"
   eval $cmd; rtn=$?
   echo "$rtn" > "$i.run.rtn"
   if [ "$rtn" -ge 100 ]
   then
     cat "$i.run.out" "$i.run.err"
     exec lldb $base_cmd -- $i
   fi
   cat "$i.run.err"
   
   expect out
   expect err
   expect rtn
done

exit $fail
