#!/bin/sh
expect() {
  _n="$1"
  if test -f "$i.exp.$_n"
  then
    echo "    Expectations in $i.run.$_n:"
    while read expect
    do
      echo "      Expecting '$expect'"
      if ! fgrep -F -e "$expect" "$i.run.$_n" >/dev/null
      then
        echo "      FAIL: Expected '$expect'" 1>&2
        fail=`expr $fail + 1`
      fi
    done < "$i.exp.$_n"
  fi
}

pass=0; fail=0
base_cmd="$1"; shift
for i in "$@"
do
  eval cmd="\"$base_cmd\""
   cmd="$cmd $i > $i.run.out 2> $i.run.err"
   echo "  Test: $i"
   echo "  Run: $cmd"
   eval $cmd; rtn=$?
   echo "$rtn" > "$i.run.rtn"
   if [ "$rtn" -ge 100 ]
   then
     cat "$i.run.out" "$i.run.err"
     exec lldb $base_cmd -- $i
   fi
   [ -n "$RUN_TEST_VERBOSE" ] && cat "$i.run.err"
   
   expect out
   expect err
   expect rtn
done

exit $fail
